android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
# AGP 8 默认非传递 R；启用 AndroidX
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=true
android.suppressUnsupportedCompileSdk=34,35
